language: java
jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# s3로 알집해서 전송하기
# before_deploy:
#  - zip -r myBlog *
#  - mkdir -p deploy
#  - mv myBlog.zip deploy/myBlog.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: myblog-s3 # S3 버킷
    region: ap-northeast-2 # 아시아 태평양 (서울)
    skip_cleanup: true
    acl: public_read
    #local_dir: deploy #zip만 추가하기 위해 s3에 넣을 dir을 deploy 폴더로 지정한다.
    wait-until-deployed: true
    on:
      repo: bactoria/ToyProject-Blog-REST #Github 주소
      branch: master


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
       - bactoria@gmail.com
